# Lychee configuration
accept = [200, 403, 410, 429, 502, 503]
exclude = [
  '\[\[.*\]\]',
  "^/[A-Z]:/",
  "https://www.npmjs.com/.*",
  "https://github.com/.*",
  "https://www.linuxfoundation.org/.*",
  "https://medium.com/.*",
  "https://deepwiki.com/.*",
  "https://javascript.info/.*",
  "https://blog.jetbrains.com/.*",
  "http://blog.modelcontextprotocol.io/.*",
]
exclude_path = [
  "README.md",
  ".vault/audit/",
  ".vault/research/",
  ".vault\\\\audit\\\\",
  ".vault\\\\research\\\\",
  ".vaultspec/rules/skills/",
  ".vaultspec\\\\rules\\\\skills\\\\",
]
no_progress = true
verbose = "info"
