"""Mutation of a consumer's ``pyproject.toml``: apply / remove the cu130
block and the low-level tomlkit helpers that materialise or drop it.

Every write crosses the FS boundary through a single
:func:`vaultspec_core.core.helpers.atomic_write`, preserving the file's
original line endings, trailing-newline shape, and all unrelated user
content via tomlkit's round-trip semantics.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Final, cast

import tomlkit
from tomlkit import TOMLDocument
from tomlkit.items import AoT, InlineTable
from vaultspec_core.core.helpers import (  # pyright: ignore[reportMissingTypeStubs]
    atomic_write,
)

from ._constants import (
    _TABLE_LIKE_TYPES,  # pyright: ignore[reportPrivateUsage]  # intra-package constant
    CU130_INDEX_NAME,
    CU130_INDEX_URL,
    CU130_MARKER,
    DIRECT_TORCH_REQUIREMENT,
    PatchReport,
    TableLike,
    TorchConfigAction,
    TorchConfigState,
)
from ._inspect import (
    classify_doc,
    detect_crlf,
    detect_state,
    get_indices_aot,
    get_tool_uv_table,
    is_half_applied,
    load_pyproject,
    match_index_entry,
    match_source_entry,
)

if TYPE_CHECKING:
    from pathlib import Path


def _tget(mapping: TableLike | TOMLDocument, key: str) -> object:
    """Typed wrapper for tomlkit Container.get() which returns Unknown.

    tomlkit's Container inherits from an unparameterised dict, so
    .get() has return type ``Unknown | None`` in strict mode.
    Centralising the cast here keeps all other call sites clean.
    """
    return cast("object", mapping.get(key))  # pyright: ignore[reportUnknownMemberType]


def manual_snippet() -> str:
    """Return the canonical cu130 block as a copy-pasteable string.

    The cu130 portion of the snippet is generated by running the same
    ``_ensure_*`` helpers ``apply_patch`` uses against an empty
    ``tomlkit`` document and serialising the result. The educational
    comment block (about direct-dep promotion under ``uv``) is appended
    as a separate constant. This guarantees byte-equality between the
    snippet and what ``apply_patch`` actually writes - drift between
    the README, install logs, and runtime CPU_ONLY error message is
    structurally impossible.
    """
    doc = tomlkit.document()
    _ensure_tool_uv_index(doc)
    _ensure_torch_source(doc)
    cu130_block = tomlkit.dumps(doc)
    return "\n" + cu130_block + _SNIPPET_DIRECT_DEP_COMMENT


_SNIPPET_DIRECT_DEP_COMMENT: Final[str] = (
    "\n"
    "# uv ignores [tool.uv.sources] for purely-transitive deps.\n"
    f"# Add torch as a direct dep too, e.g. in [project].dependencies\n"
    f'# or [dependency-groups].dev:  "{DIRECT_TORCH_REQUIREMENT}"\n'
)


def preview_patch(pyproject: Path) -> str:
    """Return the TOML snippet ``apply_patch`` would write.

    Returns an empty string when state is ``CANONICAL`` (nothing to
    do) or ``CUSTOMISED`` (apply refuses). Returns
    :func:`manual_snippet` for ``MISSING`` and ``NO_PROJECT_FILE``.
    """
    state = detect_state(pyproject)
    if state in (TorchConfigState.MISSING, TorchConfigState.NO_PROJECT_FILE):
        return manual_snippet()
    return ""


def apply_patch(pyproject: Path) -> PatchReport:
    """Write the canonical cu130 block into ``pyproject``.

    Idempotent:
    - ``CANONICAL`` → ``action="already"``, no write.
    - ``CUSTOMISED`` → ``action="conflict"`` with conflicts listed,
      no write.
    - ``NO_PROJECT_FILE`` → ``action="absent"``, no write.
    - ``MISSING`` → write via
      :func:`vaultspec_core.core.helpers.atomic_write`,
      ``action="applied"``.

    Preserves all user comments, key ordering, and whitespace in the
    rest of the document via tomlkit's round-trip semantics.
    """
    report = PatchReport(action=TorchConfigAction.SKIPPED, path=pyproject)
    doc = load_pyproject(pyproject)
    if doc is None:
        report.action = TorchConfigAction.ABSENT
        return report

    state, conflicts = classify_doc(doc)
    if state == TorchConfigState.CANONICAL:
        report.action = TorchConfigAction.ALREADY
        return report
    if state == TorchConfigState.CUSTOMISED:
        report.action = TorchConfigAction.CONFLICT
        report.conflicts = conflicts
        return report

    # MISSING → write.
    uses_crlf = detect_crlf(pyproject)
    original_bytes = pyproject.read_bytes()
    _ensure_tool_uv_index(doc)
    _ensure_torch_source(doc)
    new_text = tomlkit.dumps(doc)
    # Reparse to confirm validity before the write crosses the FS boundary.
    tomlkit.parse(new_text)
    if uses_crlf:
        # tomlkit emits LF; restore the file's original CRLF so the
        # diff stays minimal. tomlkit's parser accepts both endings,
        # so the validation reparse above still applies.
        new_text = new_text.replace("\n", "\r\n")
    # Preserve the file's original trailing-newline shape so both
    # apply and remove are EOF-neutral. Necessary for the ADR's
    # symmetric-mirror byte-equality promise (apply→remove leaves the
    # file byte-identical to the pre-apply content). BEHAV-01.
    new_text = _match_trailing_newline(original_bytes, new_text, uses_crlf=uses_crlf)
    atomic_write(pyproject, new_text)
    report.action = TorchConfigAction.APPLIED
    report.preview = manual_snippet()
    return report


def remove_patch(pyproject: Path) -> PatchReport:
    """Remove the canonical cu130 block from ``pyproject``.

    Symmetric inverse of :func:`apply_patch`:
    - ``MISSING`` or ``NO_PROJECT_FILE`` → ``action="absent"``.
    - ``CUSTOMISED`` → ``action="skipped"`` with conflicts listed;
      file unchanged.
    - ``CANONICAL`` → remove only our entries, drop any now-empty
      containers, ``action="removed"``.

    After removal, the file should reparse as valid TOML and all
    user-owned content outside the cu130 block is preserved.
    """
    report = PatchReport(action=TorchConfigAction.SKIPPED, path=pyproject)
    doc = load_pyproject(pyproject)
    if doc is None:
        report.action = TorchConfigAction.ABSENT
        return report

    state, conflicts = classify_doc(doc)
    if state == TorchConfigState.MISSING:
        report.action = TorchConfigAction.ABSENT
        return report
    if state == TorchConfigState.CUSTOMISED:
        # Half-applied edge case (one half canonical, the other simply
        # absent - no per-half conflict, no unsupported shape). The
        # default classifier flags this as CUSTOMISED so apply refuses
        # to "complete" it, but the present half IS rag's canonical
        # shape - uninstall can safely drop it. Without this branch
        # uninstall leaves an orphan rag-named entry behind. TOML-02.
        if is_half_applied(doc):
            # Fall through to the normal CANONICAL→remove path. The
            # per-half drop helpers (``_drop_cu130_index`` /
            # ``_drop_torch_source``) are no-ops on absent halves.
            pass
        else:
            report.action = TorchConfigAction.SKIPPED
            report.conflicts = conflicts
            return report

    # CANONICAL (or half-applied) → remove. Capture the trailing-newline shape pre-read
    # so the symmetric-mirror promise (apply→remove leaves the file
    # byte-identical to the pre-apply content) holds - tomlkit's
    # ``dumps`` always emits a single trailing LF, which can append
    # one extra byte if the original ended without one. BEHAV-01.
    uses_crlf = detect_crlf(pyproject)
    original_bytes = pyproject.read_bytes()
    _drop_cu130_index(doc)
    _drop_torch_source(doc)
    new_text = tomlkit.dumps(doc)
    tomlkit.parse(new_text)
    if uses_crlf:
        new_text = new_text.replace("\n", "\r\n")
    new_text = _match_trailing_newline(original_bytes, new_text, uses_crlf=uses_crlf)
    atomic_write(pyproject, new_text)
    report.action = TorchConfigAction.REMOVED
    return report


def _match_trailing_newline(
    original_bytes: bytes, new_text: str, *, uses_crlf: bool
) -> str:
    """Restore the original file's trailing-newline shape on ``new_text``.

    tomlkit's ``dumps`` always emits exactly one trailing LF.
    Real-world pyproject files vary: some end with LF, some with two
    LFs (POSIX convention with a blank final line), some with no
    trailing newline at all. Without this normalisation, ``apply →
    remove`` would silently shift the file's terminator shape,
    breaking the ADR's "symmetric mirror - leaves the file byte-
    identical to its pre-apply content" promise.
    """
    eol = "\r\n" if uses_crlf else "\n"
    eol_bytes = b"\r\n" if uses_crlf else b"\n"

    # Count the trailing-newline run on the original (in the chosen
    # eol). Compare with the trailing-newline run on tomlkit's output.
    def _count_trailing(buf: bytes, sep: bytes) -> int:
        n = 0
        while buf.endswith(sep):
            n += 1
            buf = buf[: -len(sep)]
        return n

    original_trail = _count_trailing(original_bytes, eol_bytes)
    new_bytes = new_text.encode("utf-8")
    current_trail = _count_trailing(new_bytes, eol_bytes)
    if current_trail == original_trail:
        return new_text
    # Surgically strip exactly the EOL run tomlkit emitted, then append
    # the original count. ``rstrip("\r\n")`` would over-strip any
    # adjacent CR/LF chars that aren't part of the trailing run; using
    # the counted slice keeps any non-newline trailing whitespace
    # intact (rare in TOML but cheap to preserve).
    stripped = new_text[: -current_trail * len(eol)] if current_trail > 0 else new_text
    return stripped + eol * original_trail


def write_doc_preserving_shape(pyproject: Path, doc: TOMLDocument) -> None:
    uses_crlf = detect_crlf(pyproject)
    original_bytes = pyproject.read_bytes()
    new_text = tomlkit.dumps(doc)
    tomlkit.parse(new_text)
    if uses_crlf:
        new_text = new_text.replace("\n", "\r\n")
    new_text = _match_trailing_newline(original_bytes, new_text, uses_crlf=uses_crlf)
    atomic_write(pyproject, new_text)


# ---------------------------------------------------------------------------
# tomlkit mutation helpers
# ---------------------------------------------------------------------------


def _get_or_create_tool_uv(doc: TOMLDocument) -> TableLike:
    """Return the writable ``[tool.uv]`` table, creating it if absent.

    Extracted so :func:`_ensure_tool_uv_index` and
    :func:`_ensure_torch_source` share a single source of truth for
    how the ``[tool]`` → ``[tool.uv]`` hierarchy is materialised.
    Raises if either level exists but isn't a table (refuses to
    silently clobber a user-owned key).

    Accepts both :class:`tomlkit.items.Table` and
    :class:`tomlkit.container.OutOfOrderTableProxy`. Both expose the
    Mapping API we exercise here (``setdefault`` / ``__setitem__``);
    the proxy is what tomlkit returns whenever ``[tool.X]`` sub-tables
    are interleaved with unrelated sections.
    """
    tool = doc.setdefault("tool", tomlkit.table())
    if not isinstance(tool, _TABLE_LIKE_TYPES):
        raise TypeError("pyproject.toml [tool] is not a table")
    uv = tool.setdefault("uv", tomlkit.table())
    if not isinstance(uv, _TABLE_LIKE_TYPES):
        raise TypeError("pyproject.toml [tool.uv] is not a table")
    return uv


def _ensure_tool_uv_index(doc: TOMLDocument) -> None:
    """Append ``[[tool.uv.index]]`` with the canonical cu130 entry.

    Creates ``[tool]`` and ``[tool.uv]`` if absent. Appends to the
    existing array-of-tables if one is present.
    """
    uv = _get_or_create_tool_uv(doc)
    existing: object = _tget(uv, "index")
    entry = tomlkit.table()
    entry["name"] = CU130_INDEX_NAME
    entry["url"] = CU130_INDEX_URL
    entry["explicit"] = True

    if existing is None:
        # Fresh AoT - tomlkit already inserts a trailing blank line
        # before the next top-level section, so no manual trivia
        # override is needed.
        aot = tomlkit.aot()
        aot.append(entry)  # pyright: ignore[reportUnknownMemberType]  # tomlkit AoT.append
        uv["index"] = aot
        return

    # Defensive: classify_doc already rejects single-table forms as
    # CUSTOMISED so apply_patch never reaches this function in that
    # case. Guard anyway - silently-wrong mutation is the worst
    # outcome for a user-owned file.
    if not isinstance(existing, (AoT, list)):
        raise TypeError(
            "pyproject.toml [tool.uv.index] is not an array-of-tables; "
            "refuse to mutate to avoid producing invalid TOML"
        )
    # Appending to an existing AoT: set a trailing blank line on the
    # last key's value-trivia so the appended block visually separates
    # from the next top-level section. Without this, the new block
    # lands flush against the following section header and produces
    # a noisy git diff that breaks the "preserve user formatting"
    # reason for using tomlkit. TOML-04.
    last_value = entry.value.body[-1][1]
    last_value.trivia.trail = "\n\n"
    cast("list[object]", existing).append(entry)


def _ensure_torch_source(doc: TOMLDocument) -> None:
    """Ensure ``[tool.uv.sources]`` has a cu130 torch entry.

    Accepts ``InlineTable`` symmetric with :func:`_torch_sources` and
    :func:`_drop_torch_source`. Without it, a project that wrote
    ``sources = { … }`` inline classifies as MISSING via the inline-
    aware detector, then crashes here with TypeError when apply tries
    to mutate.
    """
    uv = _get_or_create_tool_uv(doc)
    sources = uv.setdefault("sources", tomlkit.table())
    if not isinstance(sources, _TABLE_LIKE_TYPES):
        raise TypeError("pyproject.toml [tool.uv.sources] is not a table")

    inline = tomlkit.inline_table()
    inline["index"] = CU130_INDEX_NAME
    inline["marker"] = CU130_MARKER

    current: object = _tget(sources, "torch")
    if current is None:
        arr = tomlkit.array()
        arr.append(inline)  # pyright: ignore[reportUnknownMemberType]  # tomlkit Array
        arr.multiline(True)
        sources["torch"] = arr
        return

    if isinstance(current, list):
        cast("list[object]", current).append(inline)
        return

    # Promotion: existing single inline-table → array of two inline
    # tables. Only valid when `current` is an InlineTable; a standard
    # Table (e.g. ``[tool.uv.sources.torch]`` section form) cannot be
    # nested inside a TOML array. classify_doc already rejects that
    # shape as CUSTOMISED; guard anyway for defence-in-depth.
    if not isinstance(current, InlineTable):
        raise TypeError(
            "pyproject.toml [tool.uv.sources] torch is a standard "
            "table; refuse to promote into an inline-table array "
            "(would produce invalid TOML)"
        )
    arr = tomlkit.array()
    arr.append(current)  # pyright: ignore[reportUnknownMemberType]  # tomlkit Array
    arr.append(inline)  # pyright: ignore[reportUnknownMemberType]  # tomlkit Array
    arr.multiline(True)
    sources["torch"] = arr


def _drop_cu130_index(doc: TOMLDocument) -> None:
    """Remove the canonical cu130 entry from ``[[tool.uv.index]]``.

    OutOfOrderTableProxy quirk applies here too: re-fetch ``uv`` via
    :func:`get_tool_uv_table` immediately before ``del uv["index"]`` instead of
    holding a stale reference, so a freshly-constructed proxy carries
    consistent internal table positions.
    """
    indices = get_indices_aot(doc)
    if indices is None:
        return
    # Iterate backwards and pop in-place so user trivia (comments,
    # blank lines, custom formatting between tables) in the kept
    # entries is preserved. Rebuilding the AoT from scratch would
    # strip that metadata.
    for i in range(len(indices) - 1, -1, -1):
        raw_entry: object = cast("object", indices[i])  # pyright: ignore[reportUnknownMemberType]  # tomlkit AoT element
        if not isinstance(raw_entry, _TABLE_LIKE_TYPES):
            continue
        if match_index_entry(raw_entry) == "canonical":
            indices.pop(i)
    if len(indices) == 0:
        uv = get_tool_uv_table(doc)
        if uv is not None:
            del uv["index"]


def _drop_canonical_torch_entry(sources: object) -> None:
    if not isinstance(sources, _TABLE_LIKE_TYPES):
        return
    torch_entry: object = _tget(sources, "torch")
    if torch_entry is None:
        return

    if isinstance(torch_entry, _TABLE_LIKE_TYPES) and not isinstance(torch_entry, list):
        if match_source_entry(torch_entry) == "canonical":
            del sources["torch"]
    elif isinstance(torch_entry, list):
        torch_list = cast("list[object]", torch_entry)
        for i in range(len(torch_list) - 1, -1, -1):
            e: object = torch_list[i]
            if (
                isinstance(e, _TABLE_LIKE_TYPES)
                and match_source_entry(e) == "canonical"
            ):
                torch_list.pop(i)  # pyright: ignore[reportUnknownMemberType]  # tomlkit list
        if len(torch_list) == 0:
            del sources["torch"]


def _cleanup_empty_sources(doc: TOMLDocument, sources: object) -> None:
    if isinstance(sources, _TABLE_LIKE_TYPES) and not sources:
        uv = get_tool_uv_table(doc)
        if uv is not None:
            del uv["sources"]


def _cleanup_empty_uv_tables(doc: TOMLDocument) -> None:
    uv = get_tool_uv_table(doc)
    if uv is not None and not uv:
        tool: object = _tget(doc, "tool")
        if isinstance(tool, _TABLE_LIKE_TYPES):
            del tool["uv"]
            if not tool:
                del doc["tool"]


def _drop_torch_source(doc: TOMLDocument) -> None:
    """Remove the canonical cu130 torch entry from ``[tool.uv.sources]``.

    Always runs the end-of-function cleanup that drops empty
    ``sources`` / ``uv`` / ``tool`` tables, even when ``torch`` was
    never present or was a single-entry deletion. This matters after
    :func:`_drop_cu130_index` has already removed the index table -
    both callers run in sequence and the consumer file should end up
    without orphaned empty sections.

    OutOfOrderTableProxy quirk: tomlkit's proxy memoises the position
    of the underlying tables on construction; a ``__delitem__`` on it
    invalidates those positions and a second ``__delitem__`` against
    the SAME proxy can raise ``IndexError``. We work around it by
    re-fetching the proxy from its parent before each cascade-stage
    deletion (``del uv["sources"]`` → re-fetch → ``del tool["uv"]``).
    """
    uv = get_tool_uv_table(doc)
    if uv is None:
        return
    sources: object = _tget(uv, "sources")

    _drop_canonical_torch_entry(sources)
    _cleanup_empty_sources(doc, sources)
    _cleanup_empty_uv_tables(doc)
